---
title: "Gov 50 Final Project"
author: "Zelin Wang"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does suffering from physical and financial misfortunes (such as chronic illness/disability, and financial hardships) impact ones’ voters’ turnout? I hypothesize that suffering from physical and financial misfortunes negatively impact one’s willingness to vote. That is, if someone is suffering from long-term disability, having a chronic illness, been unemployed for more than a year, or having been evicted from home within the past year, this person is more likely not to show up to vote. My sample size is 5836 respondents to polling done by Ipsos for FiveThirtyEight. One explanatory variable of interest is whether one is experiencing long-term disability. The variable is coded=1 for yes and =2 for no. My outcome variable is based on the voter_category, always, sporadic, or rarely/never as the frequency of voting. I will compare the disabled population with those without disability, if the disabled population shows a significantly lower turnout for voting, then it will support my hypothesis.